sources:
  - name: s1
    database: hdfc_db
    schema: account_schema
    tables:
      - name: t_cust_info
      - name: customers
      - name: orders
      - name: payment  
      - name: tt_check
      - name: tt_time
      - name: t_emp
      - name: tt_inc
      - name: tt_inc1
      - name: t_dept